### ISSUE TITLE
Actual countdown date is September 12

### ISSUE THREAD

**Issue by jasonbarry** [dend/hawaiidiff#3]
🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴

We now know that Hawaii starts on 9/12/22! :D 

🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴🌴

**Comment by dend** [comment]
Thank you @jasonbarry! Merged your PR :D
