### ISSUE TITLE
Swap image with Netliwaii emoji

### ISSUE THREAD

**Issue by iKristy** [dend/hawaiidiff#5]
| Before | After |
|---|---|
| ![](https://hawaiidiff.com/src/media/android-chrome-144x144.png) | ![netliwaii](https://user-images.githubusercontent.com/7912948/156866910-e4532227-f2ac-41b8-8afb-b0f4b00f5282.png) |

**Comment by dend** [comment]
Thank you @iKristy - will get that updated!

**Comment by dend** [comment]
:shipit:
